name: Coreferee Matrix Test
on: 
  workflow_dispatch:

jobs:
  test-coreferee:
    strategy:
      matrix:
      os: [macos-latest, windows-latest, ubuntu-latest]
      python_version: [3.6, 3.7, 3.8, 3.9, 3.10]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository code
      uses: actions/checkout@v3
      with:
          ref: development

    - name: Initialize Python
      uses: actions/setup-python@v1
      with:
          python-version: {{ matrix.python_version }}
        
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          cd $GITHUB_WORKSPACE
          ls