name: Coreferee Matrix Test
on: 
  workflow_dispatch:

jobs:
  test-coreferee:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        python_version: ['3.6', '3.7', '3.8', '3.9', '3.10']
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository code
      uses: actions/checkout@v3
      with:
          ref: development

    - name: Initialize Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python_version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install spacy pytest
        
        # see https://github.com/explosion/spaCy/issues/10564
        pip uninstall click -y
        pip install "click<8"

    - name: Install spaCy models
      run: |
        spacy download de_core_news_sm
        spacy download de_core_news_md
        spacy download de_core_news_lg
        spacy download de_dep_news_trf
        spacy download pl_core_news_md
        spacy download pl_core_news_lg
        spacy download fr_core_news_sm
        spacy download fr_core_news_md
        spacy download fr_core_news_lg
        spacy download en_core_web_sm
        spacy download en_core_web_md
        spacy download en_core_web_lg
        spacy download en_core_web_trf
        
    - name: Install Coreferee
      run: |
        cd ${{ github.workspace }}
        pip install .
        python -m coreferee install de
        python -m coreferee install en
        python -m coreferee install fr
        python -m coreferee install pl

    - name: Test Coreferee
      run: |
        pytest tests
